#!/usr/bin/env bash

set -euo pipefail

assert_not_empty() {
  if [[ -z "${1}" ]]; then
    return 1
  fi
}

show_help() {
  echo "help"
}

runtime_error() {
  echo "ERROR: ${*}" >&2
  show_help >&2
  exit 1
}

main() {
  pod=""
  namespace="default"

  while [[ "${#}" -gt 0 ]]; do
    case $1 in
      -h | --help)
        show_help
        exit
        ;;
      -n | --namespace)
        namespace="${1}"
        shift
        ;;
      *)
        if [[ "${1}" == "-*" ]]; then
          runtime_error "Unknown flag"
        else
          pod="${1}"
          shift
        fi
        ;;
    esac
  done

  assert_not_empty "${pod}" || runtime_error "Pod required"

  kubectl exec -it "${pod}" --namespace "${namespace}" -- env | sort
}

main "${@}"
