#!/usr/bin/env bash

set -euo pipefail

assert_not_empty() {
  if [[ -z "${1}" ]]; then
    return 1
  fi
}

show_help() {
  echo "help"
}

runtime_error() {
  echo "ERROR: ${*}" >&2
  show_help >&2
  exit 1
}

main() {
  pod=""
  namespace=""
  container=""

  while [[ "${#}" -gt 0 ]]; do
    case $1 in
      -h | --help)
        show_help
        exit
        ;;
      -n | --namespace)
        namespace="${2}"
        shift 2
        ;;
      -c | --container)
        container="${2}"
        shift 2
        ;;
      *)
        if [[ "${1}" == "-*" ]]; then
          runtime_error "Unknown flag"
        else
          pod="${1}"
          shift
        fi
        ;;
    esac
  done

  assert_not_empty "${pod}" || runtime_error "Pod required"

  exec_command=()
  exec_command+=("kubectl exec")
  exec_command+=("${pod}")

  if [[ -n "${namespace}" ]]; then
    exec_command+=("--namespace ${namespace}")
  fi

  if [[ -n "${container}" ]]; then
    exec_command+=("--container ${container}")
  fi

  exec_command+=("-- env")

  eval "${exec_command[@]}" | sort
}

main "${@}"
