name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Create kind cluster
      uses: helm/kind-action@v1.0.0-alpha.3

    - name: Build
      run: make

    - name: End to end test
      run: make e2e-test
