name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Create kind cluster
      uses: helm/kind-action@v1.2.0

    - name: Build
      run: make

    - name: End to end test
      run: make e2e-test
