name: release

on:
  push:
    tags: "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: get tag name
        run: |
          echo ::set-env name=tag::${GITHUB_REF/refs\/tags\//}

      - name: get commit message
        run: |
          echo ::set-env name=message::$(git tag -n99 --format='%(contents)' ${{ env.tag }})

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            ${{ env.message }}
          draft: false
          prerelease: ${{contains(github.ref, 'rc')}}
